name: Unassign Inactive Issues 

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every minute for testing 

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check and unassign inactive issues
        env:
          WEB_TOKEN: ${{ secrets.WEB_TOKEN }}

        run: node .github/index.js
      