name: Unassign Inactive Issues 

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute for testing 

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check and unassign inactive issues
        uses: ./
        env:
          WEB_TOKEN: ${{ secrets.WEB_TOKEN }}

        run: node index.js
      