name: Unassign Inactive Issues

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute for testing

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Run unassign-inactive-issues action
        uses: ./actions/unassign-inactive-issues # Adjust this path if action.yml is in a different location
        with:
          githubToken: ${{ secrets.WEB_TOKEN }}
          inactivityPeriodInMinutes: 1
